# -*- coding: utf-8 -*-
"""Forca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TQwEiYqy1VLX4QOkVE5f2HX4-WmKZ5S
"""

import random

f	=	open("Coloque um arquivo txt")
lines = f.readlines()
n = random.randint(0,7)
palavra = lines[n]

acertos = ['_','_','_','_','_','_']
i=0
saida = 0
a = 0

print(acertos)
while(saida ==0):
  chute = input("Qual letra?")

  posicao = 0
  for letra in palavra:
    if(chute.upper() == letra.upper()):
      acertos[posicao] = letra
      a += 1
      if(a==6):
        saida= 1
    posicao = posicao + 1
    i += 1
    if(i == 6):
      print(acertos)
      i = 0

print('Fim	do	jogo')